-- Talvez necessario criar uma table para arquivo PDF...
-- Inserir PDF na database?
-- Descricoes so varchar?
--
DROP DATABASE IF EXISTS SISTEMAEMPREGOS;

CREATE DATABASE SISTEMAEMPREGOS;

USE SISTEMAEMPREGOS;

-- Criando tables necessarias.
CREATE TABLE EMPRESA (
	CNPJ BIGINT NOT NULL,
	NOME VARCHAR(256) NOT NULL,
	SENHA VARCHAR(64) NOT NULL,
	EMAIL VARCHAR(256) NOT NULL,
	DESCRICAO VARCHAR(256) NOT NULL,
	CIDADE VARCHAR(256) NOT NULL,
	PRIMARY KEY(CNPJ)
);

CREATE TABLE PROFISSIONAL (
	CPF BIGINT NOT NULL,
	NOME VARCHAR(256) NOT NULL,
	SENHA VARCHAR(64) NOT NULL,
	EMAIL VARCHAR(256) NOT NULL,
	TELEFONE VARCHAR(15),
	SEXO CHAR,
	DATA DATE,
	PRIMARY KEY(CPF)
);

CREATE TABLE USUARIO(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(256) NOT NULL,
	LOGIN VARCHAR(20) NOT NULL UNIQUE,
	SENHA VARCHAR(64) NOT NULL,
	PAPEL VARCHAR(10),
	PRIMARY KEY (ID)
);

-- Necessario realizar o auto_increment nos beans.
CREATE TABLE VAGA (
	ID BIGINT NOT NULL,
	CNPJEMPRESA BIGINT NOT NULL,
	DESCRICAO VARCHAR(1000),
	REMUNERACAO FLOAT NOT NULL,
	DATALIMITE DATE NOT NULL,
	PRIMARY KEY(CNPJEMPRESA, ID),
	FOREIGN KEY (CNPJEMPRESA) REFERENCES EMPRESA(CNPJ)
);

CREATE TABLE CANDIDATURA (
	IDVAGA BIGINT NOT NULL,
	CNPJEMPRESA BIGINT NOT NULL,
	CPFPROFISSIONAL BIGINT NOT NULL,
	FOREIGN KEY(CNPJEMPRESA, IDVAGA) REFERENCES VAGA(CNPJEMPRESA, ID),
	FOREIGN KEY(CPFPROFISSIONAL) REFERENCES PROFISSIONAL(CPF),
	PRIMARY KEY(IDVAGA, CNPJEMPRESA, CPFPROFISSIONAL)
);

CREATE TABLE FILE_CANDIDATURA (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	FILENAME VARCHAR(256) NOT NULL,
	FILETYPE VARCHAR(256) NOT NULL,
	DATA MEDIUMBLOB NOT NULL,
	PRIMARY KEY(ID)
);

-- Inserindo elementos exemplo.
-- Profissionais
INSERT INTO PROFISSIONAL VALUES(82128243068, "Roseval Junior", "rdmaljr@hotmail.com", "5539806798860", "123password", 'm', "2000-06-25");
INSERT INTO PROFISSIONAL VALUES(44634097052, "Marcela Ribeiro", "rdmal@hotmail.com", "5577867134261","1234password", 'f', "1999-04-15");
INSERT INTO PROFISSIONAL VALUES(35098455014, "José da SIlva", "roseval@estudante.ufscar.br", "5579768042305", "1245password", 'm', "1995-01-02");

-- Empresas
INSERT INTO EMPRESA VALUES(61189483000109, "MICROSOFT", "password123", "rdmaljr@hotmail.com", "Essa empresa vende windows", "São Carlos");
INSERT INTO EMPRESA VALUES(32989207000127, "PROGRAMAS .INC", "password1234", "rdmal@hotmail.com", "Essa empresa vende programas", "Bahia");

-- Usuarios
INSERT INTO USUARIO (NOME, LOGIN, SENHA, PAPEL) VALUES("administrador", "admin", "admin", "admin");
INSERT INTO USUARIO (NOME, LOGIN, SENHA, PAPEL) VALUES("usuario", "user", "user", "user");
-- Vagas
INSERT INTO VAGA (ID, CNPJEMPRESA, DESCRICAO, REMUNERACAO, DATALIMITE) VALUES(0, 61189483000109, "Vendedor de windows", 1000, "2020-06-02");
INSERT INTO VAGA (ID, CNPJEMPRESA, DESCRICAO, REMUNERACAO, DATALIMITE) VALUES(1, 32989207000127, "Vendedor de programas", 3000, "2020-06-10");

-- Candidaturas
INSERT INTO CANDIDATURA VALUES(0, 61189483000109, 82128243068);
INSERT INTO CANDIDATURA VALUES(1, 32989207000127, 44634097052);

-- PDFS (DEPOIS TESTAR).

-- Visualizando tables.
SELECT * FROM PROFISSIONAL;
SELECT * FROM EMPRESA;
SELECT * FROM USUARIO;
SELECT * FROM VAGA;
SELECT * FROM CANDIDATURA;
