-- Talvez necessario criar uma table para arquivo PDF...
-- Inserir PDF na database?
-- Descricoes so varchar?
--
DROP DATABASE IF EXISTS SISTEMAEMPREGOS;

CREATE DATABASE SISTEMAEMPREGOS;

USE SISTEMAEMPREGOS;

-- Ao retornar infos da empresa ou profissional, fazer um join com usuário.

-- Criando tables necessarias.
CREATE TABLE USUARIO( -- CORRETO.
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(256) NOT NULL,
	LOGIN VARCHAR(256) NOT NULL UNIQUE,
	SENHA VARCHAR(64) NOT NULL,
	PAPEL VARCHAR(20),
	PRIMARY KEY (ID)
);

-- NOME, SENHA, EMAIL DEVE VIR DE USUARIO.
CREATE TABLE EMPRESA (
	IDUSUARIO BIGINT NOT NULL,
	CNPJ BIGINT NOT NULL UNIQUE,
	DESCRICAO VARCHAR(256) NOT NULL,
	CIDADE VARCHAR(256) NOT NULL,
	PRIMARY KEY(IDUSUARIO),
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID)
	ON DELETE CASCADE
);

CREATE TABLE PROFISSIONAL (
	IDUSUARIO BIGINT NOT NULL,
	CPF BIGINT NOT NULL UNIQUE,
	TELEFONE VARCHAR(15),
	SEXO VARCHAR(9),
	NASCIMENTO DATE,
	PRIMARY KEY(IDUSUARIO),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID)
	ON DELETE CASCADE
);

-- Necessario realizar o auto_increment nos beans.
CREATE TABLE VAGA (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	IDEMPRESA BIGINT NOT NULL,
	DESCRICAO VARCHAR(256),
	REMUNERACAO FLOAT NOT NULL,
	DATALIMITE DATE NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDUSUARIO)
	ON DELETE CASCADE
);

CREATE TABLE CANDIDATURA (
	IDVAGA BIGINT NOT NULL,
	IDPROFISSIONAL BIGINT NOT NULL,
	STATUS VARCHAR(256) DEFAULT 'ABERTO',
	CURRICULO VARCHAR(256),
	PRIMARY KEY(IDVAGA, IDPROFISSIONAL),
	FOREIGN KEY(IDVAGA) REFERENCES VAGA(ID)
	ON DELETE CASCADE,
	FOREIGN KEY(IDPROFISSIONAL) REFERENCES PROFISSIONAL(IDUSUARIO)
	ON DELETE CASCADE
);

-- Inserindo elementos exemplo.
-- Usuarios
INSERT INTO USUARIO (NOME ,LOGIN ,SENHA, PAPEL) VALUES("Carlos da Silva", "admin","admin","admin");
INSERT INTO USUARIO (NOME ,LOGIN ,SENHA, PAPEL) VALUES("Roseval Junior", "rdmaljr@hotmail.com","123password","userProfissional");
INSERT INTO USUARIO (NOME ,LOGIN ,SENHA, PAPEL) VALUES("Marcela Ribeiro", "marcela@hotmail.com","1234password","userProfissional");
INSERT INTO USUARIO (NOME ,LOGIN ,SENHA, PAPEL) VALUES("José da Silva", "jose@estudante.ufscar.br","1235password","userProfissional");
INSERT INTO USUARIO (NOME ,LOGIN ,SENHA, PAPEL) VALUES("MICROSOFT", "microsoft@hotmail.com","1236password","userEmpresa");
INSERT INTO USUARIO (NOME ,LOGIN ,SENHA, PAPEL) VALUES("PROGRAMAS .INC", "roseval@estudante.ufscar.br","1237password","userEmpresa");

-- Profissionais
INSERT INTO PROFISSIONAL VALUES(2, 82128243068, "5539806798860", "m", "2000-06-25");
INSERT INTO PROFISSIONAL VALUES(3, 44634097052, "5577867134261", "f", "1999-04-15");
INSERT INTO PROFISSIONAL VALUES(4, 35098455014, "5579768042305", "m", "1995-01-02");

-- Empresas
INSERT INTO EMPRESA VALUES(5, 61189483000109, "Essa empresa vende windows", "São Carlos");
INSERT INTO EMPRESA VALUES(6, 32989207000127, "Essa empresa vende programas", "Bahia");

-- Vagas
INSERT INTO VAGA (IDEMPRESA, DESCRICAO, REMUNERACAO, DATALIMITE) VALUES(5, "Vendedor de windows", 1000.1, "2021-06-02");
INSERT INTO VAGA (IDEMPRESA, DESCRICAO, REMUNERACAO, DATALIMITE) VALUES(6, "Vendedor de programas", 3000.2, "2021-06-10");
INSERT INTO VAGA (IDEMPRESA, DESCRICAO, REMUNERACAO, DATALIMITE) VALUES(6, "Essa aqui vai dar fechada!", 3000.3, "2021-03-01");
INSERT INTO VAGA (IDEMPRESA, DESCRICAO, REMUNERACAO, DATALIMITE) VALUES(6, "Mesmo dia fica aberta!", 3000.3, "2021-05-27");

-- Candidaturas
INSERT INTO CANDIDATURA (IDVAGA, IDPROFISSIONAL, CURRICULO) VALUES(1, 2 ,"CurriculoRosevalJunior.pdf");
INSERT INTO CANDIDATURA (IDVAGA, IDPROFISSIONAL, CURRICULO) VALUES(2, 3 ,"CurriculoMarcelRibeiro.pdf");

-- Visualizando tables.
SELECT * FROM USUARIO;
SELECT * FROM PROFISSIONAL;
SELECT * FROM EMPRESA;
SELECT * FROM VAGA;
SELECT * FROM CANDIDATURA;
