DROP DATABASE IF EXISTS SISTEMAEMPREGOS;

CREATE DATABASE IF NOT EXISTS SISTEMAEMPREGOS;

USE SISTEMAEMPREGOS;

CREATE TABLE EMPRESA (
	CNPJ INT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	SENHA VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(256) NOT NULL,
	DESCRICAO VARCHAR(256),
	CIDADE VARCHAR(30)
);

CREATE TABLE PROFISSIONAL (
	CPF INT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	SENHA VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(256) NOT NULL,
	TELEFONE VARCHAR(14),
	SEXO VARCHAR(1),
	DATA DATE
);

CREATE TABLE VAGA (
	CNPJEMPRESA INT NOT NULL,
	ID INT NOT NULL,
	DESCRICAO VARCHAR(1000),
	REMUNERACAO INT,
	DATALIMITE DATE,
	PRIMARY KEY(CNPJEMPRESA, ID),
	FOREIGN KEY (CNPJEMPRESA) REFERENCES EMPRESA(CNPJ)
);

CREATE TABLE CANDIDATURA (
	IDCAN INT NOT NULL,
	CNPJEMP INT NOT NULL,
	CPFPES INT NOT NULL,
	FOREIGN KEY(CNPJEMP, IDCAN) REFERENCES VAGA(CNPJEMPRESA, ID),
	FOREIGN KEY(CPFPES) REFERENCES PROFISSIONAL(CPF),
	PRIMARY KEY(IDCAN, CNPJEMP,CPFPES)
);

INSERT INTO PROFISSIONAL VALUES(495575, "ROSEVAL", "12345", "ROSE@GMAIL.COM", "454548", "f", "1998-07-19");
INSERT INTO PROFISSIONAL VALUES(495535, "ROSEVAL", "12345", "ROSE@GMAIL.COM", "454548", "f", "1998-07-19");

INSERT INTO EMPRESA VALUES(49152, "APPLE", "ANDROIDLIXO", "APPLE@APPLE.COM", "484541", "SC");

INSERT INTO VAGA VALUES(49152, 2, "QQRCOISA", 1500, "1998-07-19");

INSERT INTO CANDIDATURA VALUES(2,49152,495575);
INSERT INTO CANDIDATURA VALUES(2,49152,495535);

SELECT * FROM PROFISSIONAL;
SELECT * FROM EMPRESA;
SELECT * FROM VAGA;
SELECT * FROM CANDIDATURA;
